name: Node CI

on:
  pull_request:
    branches:
      - "*/*"
      - "*"
      - "!master"
  push:
    branches:
      - "*/*"
      - "*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@preview
        with:
          path: ./node_modules
          key: ${{ matrix.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-node-
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
        env:
          MONGODB_URI: "testtest"
          SECRET_KEY: "hoge"
